# permissions for end users to view observabilityuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: observabilityui-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: observability-ui-operator
    app.kubernetes.io/part-of: observability-ui-operator
    app.kubernetes.io/managed-by: kustomize
  name: observabilityui-viewer-role
rules:
  - apiGroups:
      - observability-ui.openshift.io
    resources:
      - observabilityuis
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - observability-ui.openshift.io
    resources:
      - observabilityuis/status
    verbs:
      - get
